-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.sales_transaction
(
    transaction_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL
);

CREATE TABLE IF NOT EXISTS public.product_master
(
    product_id integer NOT NULL,
    product_name character varying(100) NOT NULL,
    retail_price integer NOT NULL,
    product_class_id integer NOT NULL,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.product_class_master
(
    product_class_id integer NOT NULL,
    product_class_name character varying(100) NOT NULL,
    PRIMARY KEY (product_class_id)
);

ALTER TABLE IF EXISTS public.sales_transaction
    ADD CONSTRAINT product FOREIGN KEY (product_id)
    REFERENCES public.product_master (product_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.product_master
    ADD CONSTRAINT product_class FOREIGN KEY (product_class_id)
    REFERENCES public.product_class_master (product_class_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;